const wordList = [
  { word: "cost", hint: "The amount a buyer pays for good bought." },
  { word: "selling", hint: "The amount the goods are sold for." },
  { word: "loss", hint: "When the amount he bought his good is greater than the amount he sells it for." },
  { word: "profit", hint: "To calculate this percent, a businessman divides his profit by his cost." },
  { word: "cost", hint: "To calculate the profit percent, a businessman divides his profit by this." },
  { word: "hundred", hint: "To calculate the profit percent, a businessman multiplies the fraction by this." },
  { word: "equilateral", hint: "A triangle with all sides equal." },
  { word: "isosceles", hint: "A triangle with at least two sides equal." },
  { word: "scalene", hint: "A triangle with no sides equal." },
  { word: "rectangle", hint: "A quadrilateral with opposite sides equal and four right angles." },
  { word: "square", hint: "A quadrilateral with all sides equal and four right angles." },
  { word: "parallelogram", hint: "A quadrilateral with opposite sides parallel and equal." },
  { word: "trapezium", hint: "A quadrilateral with one pair of opposite sides parallel." },
  { word: "triangle", hint: "A polygon with three sides and three angles." },
  { word: "circle", hint: "A round shape with all points the same distance from the center." },
  { word: "length", hint: "The longer side of a rectangle." },
  { word: "width", hint: "The shorter side of a rectangle." },
  { word: "side", hint: "The length of one of the equal sides of a square." },
  { word: "base", hint: "The bottom side of a triangle or parallelogram." },
  { word: "height", hint: "The perpendicular distance from the base to the topmost point." },
  { word: "radius", hint: "The distance from the center of a circle to any point on its circumference." },
  { word: "diameter", hint: "The distance across a circle through its center, equal to twice the radius." },
  { word: "pi", hint: "The mathematical constant used to calculate the area of a circle (22/7)." },
  { word: "area", hint: "The amount of space inside a shape." },
  { word: "rectangle", hint: "Calculated as length multiplied by width. Which area is this?" },
  { word: "square", hint: "Calculated as side multiplied by side. Which area is this?" },
  { word: "parallelogram", hint: "Calculated as base multiplied by height. Which area is this?" },
  { word: "trapezium", hint: "Calculated as half the sum of the parallel sides multiplied by height. Which area is this?" },
  { word: "triangle", hint: "Calculated as half the base multiplied by height. Which area is this?" },
  { word: "circle", hint: "Calculated as 22/7 multiplied by the radius squared. Which area is this?" }
];