const wordList = [
  // === BEGINNER LEVEL (Grades 1-6) === [200 words]
  
  // Basic Arithmetic Operations
  { word: "addition", hint: "The process of combining numbers to find their total.", level: "easy" },
  { word: "subtraction", hint: "The process of taking one number away from another.", level: "easy" },
  { word: "multiplication", hint: "Repeated addition of the same number.", level: "easy" },
  { word: "division", hint: "Splitting into equal parts or groups.", level: "easy" },
  { word: "sum", hint: "The result of adding numbers together.", level: "easy" },
  { word: "difference", hint: "The result of subtracting one number from another.", level: "easy" },
  { word: "product", hint: "The result of multiplying numbers.", level: "easy" },
  { word: "quotient", hint: "The result of dividing one number by another.", level: "easy" },
  { word: "equals", hint: "Having the same value or amount.", level: "easy" },
  { word: "plus", hint: "The symbol or operation for addition.", level: "easy" },
  { word: "minus", hint: "The symbol or operation for subtraction.", level: "easy" },
  { word: "times", hint: "Another word for multiplication.", level: "easy" },
  { word: "divided by", hint: "The operation that splits a number into equal parts.", level: "easy" },
  { word: "remainder", hint: "The amount left over after division.", level: "easy" },
  { word: "addend", hint: "A number being added to another number.", level: "easy" },
  { word: "minuend", hint: "The number from which another number is subtracted.", level: "easy" },
  { word: "subtrahend", hint: "The number being subtracted from another.", level: "easy" },
  { word: "factor", hint: "A number that divides another number exactly.", level: "easy" },
  { word: "dividend", hint: "The number being divided.", level: "easy" },
  { word: "divisor", hint: "The number by which another is divided.", level: "easy" },
  
  // Numbers & Counting
  { word: "number", hint: "A mathematical value used for counting or measuring.", level: "easy" },
  { word: "counting", hint: "Determining how many objects there are.", level: "easy" },
  { word: "zero", hint: "The number representing nothing or absence of quantity.", level: "easy" },
  { word: "one", hint: "The first counting number.", level: "easy" },
  { word: "whole numbers", hint: "Numbers without fractions or decimals; 0, 1, 2, 3...", level: "easy" },
  { word: "digits", hint: "The symbols 0-9 used to write numbers.", level: "easy" },
  { word: "place value", hint: "The value of a digit based on its position in a number.", level: "easy" },
  { word: "ones", hint: "The place value for single items.", level: "easy" },
  { word: "tens", hint: "The place value representing groups of ten.", level: "easy" },
  { word: "hundreds", hint: "The place value representing groups of one hundred.", level: "easy" },
  { word: "thousands", hint: "The place value representing groups of one thousand.", level: "easy" },
  { word: "millions", hint: "The place value representing groups of one million.", level: "easy" },
  { word: "greater than", hint: "A comparison showing one quantity is larger than another.", level: "easy" },
  { word: "less than", hint: "A comparison showing one quantity is smaller than another.", level: "easy" },
  { word: "equal to", hint: "Having exactly the same value.", level: "easy" },
  { word: "even numbers", hint: "Numbers divisible by 2; they end in 0, 2, 4, 6, or 8.", level: "easy" },
  { word: "odd numbers", hint: "Numbers not divisible by 2; they end in 1, 3, 5, 7, or 9.", level: "easy" },
  { word: "number line", hint: "A straight line with numbers placed at equal intervals.", level: "easy" },
  { word: "positive numbers", hint: "Numbers greater than zero.", level: "easy" },
  { word: "negative numbers", hint: "Numbers less than zero.", level: "easy" },
  { word: "integer", hint: "A whole number that can be positive, negative, or zero.", level: "easy" },
  { word: "natural numbers", hint: "Counting numbers starting from 1.", level: "easy" },
  { word: "rounding", hint: "Approximating a number to a specified place value.", level: "easy" },
  { word: "estimate", hint: "An approximate calculation or judgment of value.", level: "easy" },
  { word: "compare", hint: "To examine the difference between numbers or quantities.", level: "easy" },
  { word: "order", hint: "Arranging numbers from least to greatest or vice versa.", level: "easy" },
  
  // Fractions & Decimals
  { word: "fraction", hint: "A part of a whole, written as one number over another.", level: "easy" },
  { word: "numerator", hint: "The top number in a fraction showing how many parts are taken.", level: "easy" },
  { word: "denominator", hint: "The bottom number in a fraction showing total equal parts.", level: "easy" },
  { word: "unit fraction", hint: "A fraction with numerator 1, such as 1/2 or 1/3.", level: "easy" },
  { word: "proper fraction", hint: "A fraction where the numerator is less than the denominator.", level: "easy" },
  { word: "improper fraction", hint: "A fraction where the numerator is greater than or equal to the denominator.", level: "easy" },
  { word: "mixed number", hint: "A whole number combined with a fraction.", level: "easy" },
  { word: "equivalent fractions", hint: "Different fractions that represent the same value.", level: "easy" },
  { word: "simplest form", hint: "A fraction where numerator and denominator have no common factors except 1.", level: "easy" },
  { word: "decimal", hint: "A number that uses a decimal point to show parts of a whole.", level: "easy" },
  { word: "decimal point", hint: "The dot separating the whole number from fractional parts.", level: "easy" },
  { word: "tenths", hint: "The first decimal place to the right of the decimal point.", level: "easy" },
  { word: "hundredths", hint: "The second decimal place to the right of the decimal point.", level: "easy" },
  { word: "thousandths", hint: "The third decimal place to the right of the decimal point.", level: "easy" },
  { word: "half", hint: "One of two equal parts; 1/2.", level: "easy" },
  { word: "third", hint: "One of three equal parts; 1/3.", level: "easy" },
  { word: "quarter", hint: "One of four equal parts; 1/4.", level: "easy" },
  { word: "reduce", hint: "To simplify a fraction to its lowest terms.", level: "easy" },
  { word: "common denominator", hint: "A shared denominator for two or more fractions.", level: "easy" },
  { word: "like fractions", hint: "Fractions that have the same denominator.", level: "easy" },
  
  // Basic Geometry
  { word: "shape", hint: "The form or outline of an object.", level: "easy" },
  { word: "triangle", hint: "A polygon with three sides and three angles.", level: "easy" },
  { word: "square", hint: "A quadrilateral with four equal sides and four right angles.", level: "easy" },
  { word: "rectangle", hint: "A quadrilateral with four right angles and opposite sides equal.", level: "easy" },
  { word: "circle", hint: "A round shape where all points are equidistant from the center.", level: "easy" },
  { word: "oval", hint: "An elongated circle shape.", level: "easy" },
  { word: "pentagon", hint: "A polygon with five sides.", level: "easy" },
  { word: "hexagon", hint: "A polygon with six sides.", level: "easy" },
  { word: "octagon", hint: "A polygon with eight sides.", level: "easy" },
  { word: "cube", hint: "A 3D shape with six square faces.", level: "easy" },
  { word: "sphere", hint: "A perfectly round 3D object like a ball.", level: "easy" },
  { word: "cone", hint: "A 3D shape with a circular base and pointed top.", level: "easy" },
  { word: "cylinder", hint: "A 3D shape with two parallel circular bases.", level: "easy" },
  { word: "pyramid", hint: "A 3D shape with a polygon base and triangular sides meeting at a point.", level: "easy" },
  { word: "edge", hint: "The line where two faces of a solid meet.", level: "easy" },
  { word: "face", hint: "A flat surface of a solid shape.", level: "easy" },
  { word: "vertex", hint: "A corner point where edges meet.", level: "easy" },
  { word: "side", hint: "A line segment forming part of a polygon.", level: "easy" },
  { word: "corner", hint: "The point where two sides meet.", level: "easy" },
  { word: "line", hint: "A straight path extending in both directions infinitely.", level: "easy" },
  { word: "point", hint: "An exact location in space with no size.", level: "easy" },
  { word: "ray", hint: "A line with one endpoint extending infinitely in one direction.", level: "easy" },
  { word: "line segment", hint: "A part of a line with two endpoints.", level: "easy" },
  { word: "curve", hint: "A smoothly flowing line that is not straight.", level: "easy" },
  { word: "symmetry", hint: "When one half of a shape is a mirror image of the other half.", level: "easy" },
  { word: "line of symmetry", hint: "A line dividing a shape into two identical halves.", level: "easy" },
  { word: "congruent", hint: "Having the same shape and size.", level: "easy" },
  
  // Measurement
  { word: "measure", hint: "To find the size, length, or amount of something.", level: "easy" },
  { word: "length", hint: "The measurement of something from end to end.", level: "easy" },
  { word: "width", hint: "The measurement from side to side.", level: "easy" },
  { word: "height", hint: "The measurement from bottom to top.", level: "easy" },
  { word: "perimeter", hint: "The distance around the outside of a shape.", level: "easy" },
  { word: "area", hint: "The amount of space inside a 2D shape.", level: "easy" },
  { word: "volume", hint: "The amount of space occupied by a 3D object.", level: "easy" },
  { word: "capacity", hint: "The amount a container can hold.", level: "easy" },
  { word: "weight", hint: "How heavy something is.", level: "easy" },
  { word: "mass", hint: "The amount of matter in an object.", level: "easy" },
  { word: "time", hint: "The ongoing sequence of events measured in hours, minutes, and seconds.", level: "easy" },
  { word: "temperature", hint: "How hot or cold something is.", level: "easy" },
  { word: "distance", hint: "The amount of space between two points.", level: "easy" },
  { word: "meter", hint: "The basic unit of length in the metric system.", level: "easy" },
  { word: "centimeter", hint: "One hundredth of a meter.", level: "easy" },
  { word: "millimeter", hint: "One thousandth of a meter.", level: "easy" },
  { word: "kilometer", hint: "One thousand meters.", level: "easy" },
  { word: "inch", hint: "A unit of length in the imperial system.", level: "easy" },
  { word: "foot", hint: "A unit of length equal to 12 inches.", level: "easy" },
  { word: "yard", hint: "A unit of length equal to 3 feet.", level: "easy" },
  { word: "mile", hint: "A unit of length equal to 5,280 feet.", level: "easy" },
  { word: "gram", hint: "A basic unit of mass in the metric system.", level: "easy" },
  { word: "kilogram", hint: "One thousand grams.", level: "easy" },
  { word: "liter", hint: "A basic unit of volume in the metric system.", level: "easy" },
  { word: "milliliter", hint: "One thousandth of a liter.", level: "easy" },
  { word: "ounce", hint: "A unit of weight in the imperial system.", level: "easy" },
  { word: "pound", hint: "A unit of weight equal to 16 ounces.", level: "easy" },
  { word: "cup", hint: "A unit of volume used in cooking.", level: "easy" },
  { word: "pint", hint: "A unit of volume equal to 2 cups.", level: "easy" },
  { word: "quart", hint: "A unit of volume equal to 2 pints.", level: "easy" },
  { word: "gallon", hint: "A unit of volume equal to 4 quarts.", level: "easy" },
  
  // Time & Money
  { word: "hour", hint: "A unit of time equal to 60 minutes.", level: "easy" },
  { word: "minute", hint: "A unit of time equal to 60 seconds.", level: "easy" },
  { word: "second", hint: "The basic unit of time.", level: "easy" },
  { word: "clock", hint: "An instrument for measuring and showing time.", level: "easy" },
  { word: "calendar", hint: "A chart showing days, weeks, and months of a year.", level: "easy" },
  { word: "money", hint: "Currency used to buy goods and services.", level: "easy" },
  { word: "dollar", hint: "The basic unit of currency in the United States.", level: "easy" },
  { word: "cent", hint: "One hundredth of a dollar.", level: "easy" },
  { word: "penny", hint: "A coin worth one cent.", level: "easy" },
  { word: "nickel", hint: "A coin worth five cents.", level: "easy" },
  { word: "dime", hint: "A coin worth ten cents.", level: "easy" },
  { word: "quarter", hint: "A coin worth twenty-five cents.", level: "easy" },
  { word: "change", hint: "Money returned when payment exceeds the cost.", level: "easy" },
  { word: "cost", hint: "The amount of money needed to buy something.", level: "easy" },
  { word: "total", hint: "The complete sum or amount.", level: "easy" },
  
  // Patterns & Sequences
  { word: "pattern", hint: "A repeated design or sequence.", level: "easy" },
  { word: "sequence", hint: "An ordered list following a rule.", level: "easy" },
  { word: "skip counting", hint: "Counting by numbers other than 1.", level: "easy" },
  { word: "repeating pattern", hint: "A pattern that continues in the same way.", level: "easy" },
  { word: "growing pattern", hint: "A pattern that increases by a fixed amount.", level: "easy" },
  { word: "rule", hint: "A statement describing a mathematical relationship.", level: "easy" },
  
  // Data & Graphs
  { word: "graph", hint: "A visual representation of data.", level: "easy" },
  { word: "chart", hint: "A visual display of information.", level: "easy" },
  { word: "bar graph", hint: "A graph using bars to show data.", level: "easy" },
  { word: "picture graph", hint: "A graph using pictures to represent data.", level: "easy" },
  { word: "line plot", hint: "A graph showing data points along a number line.", level: "easy" },
  { word: "tally", hint: "Marks used to count items.", level: "easy" },
  { word: "data", hint: "Information collected for analysis.", level: "easy" },
  { word: "survey", hint: "Collecting information by asking questions.", level: "easy" },
  { word: "table", hint: "An organized arrangement of data in rows and columns.", level: "easy" },
  { word: "label", hint: "Text identifying parts of a graph or diagram.", level: "easy" },
  { word: "title", hint: "The name of a graph or chart.", level: "easy" },
  { word: "scale", hint: "The range of values on a graph axis.", level: "easy" },
  
  // Problem Solving
  { word: "problem", hint: "A question requiring a solution.", level: "easy" },
  { word: "solve", hint: "To find the answer to a problem.", level: "easy" },
  { word: "solution", hint: "The answer to a problem.", level: "easy" },
  { word: "strategy", hint: "A plan for solving a problem.", level: "easy" },
  { word: "guess and check", hint: "A strategy of trying answers until finding the correct one.", level: "easy" },
  { word: "work backward", hint: "Starting from the end result to find the beginning.", level: "easy" },
  { word: "draw a picture", hint: "Using a visual representation to solve a problem.", level: "easy" },
  { word: "make a list", hint: "Writing out possibilities to organize thinking.", level: "easy" },
  { word: "find a pattern", hint: "Looking for repeating relationships in numbers.", level: "easy" },
  { word: "word problem", hint: "A math problem presented in written form.", level: "easy" },
  { word: "operation", hint: "A mathematical process like addition or subtraction.", level: "easy" },
  { word: "inverse operation", hint: "The opposite operation that undoes another.", level: "easy" },
  { word: "reasonable", hint: "Making sense or being logical.", level: "easy" },
  { word: "check", hint: "To verify an answer is correct.", level: "easy" },
  
  // === INTERMEDIATE LEVEL (Grades 7-9) === [150 words]
  
  // Algebra Basics
  { word: "algebra", hint: "Branch of mathematics using symbols and letters to represent numbers.", level: "medium" },
  { word: "variable", hint: "A symbol, usually a letter, that represents an unknown number.", level: "medium" },
  { word: "expression", hint: "A combination of numbers, variables, and operations.", level: "medium" },
  { word: "equation", hint: "A mathematical statement that two expressions are equal.", level: "medium" },
  { word: "inequality", hint: "A mathematical statement comparing expressions that are not equal.", level: "medium" },
  { word: "coefficient", hint: "A number multiplying a variable in an algebraic expression.", level: "medium" },
  { word: "constant", hint: "A fixed value that does not change.", level: "medium" },
  { word: "term", hint: "A single number or variable, or numbers and variables multiplied together.", level: "medium" },
  { word: "like terms", hint: "Terms with the same variable raised to the same power.", level: "medium" },
  { word: "combine like terms", hint: "Adding or subtracting terms with the same variable part.", level: "medium" },
  { word: "simplify", hint: "To reduce an expression to its simplest form.", level: "medium" },
  { word: "evaluate", hint: "To find the numerical value of an expression.", level: "medium" },
  { word: "substitute", hint: "To replace a variable with a number.", level: "medium" },
  { word: "isolate", hint: "To get a variable alone on one side of an equation.", level: "medium" },
  { word: "linear equation", hint: "An equation whose graph is a straight line.", level: "medium" },
  { word: "slope", hint: "The steepness of a line, calculated as rise over run.", level: "medium" },
  { word: "y-intercept", hint: "The point where a line crosses the y-axis.", level: "medium" },
  { word: "x-intercept", hint: "The point where a line crosses the x-axis.", level: "medium" },
  { word: "ordered pair", hint: "Two numbers written in a specific order to locate a point.", level: "medium" },
  { word: "coordinate", hint: "A number representing position on a number line or plane.", level: "medium" },
  { word: "origin", hint: "The point (0,0) where axes intersect on a coordinate plane.", level: "medium" },
  { word: "quadrant", hint: "One of four sections of a coordinate plane.", level: "medium" },
  { word: "system of equations", hint: "Two or more equations with the same variables.", level: "medium" },
  { word: "exponent", hint: "A number showing how many times to multiply a base by itself.", level: "medium" },
  { word: "base", hint: "The number being multiplied by itself in a power.", level: "medium" },
  { word: "power", hint: "A number expressed using a base and exponent.", level: "medium" },
  { word: "square", hint: "To multiply a number by itself.", level: "medium" },
  { word: "square root", hint: "A number that when multiplied by itself gives the original number.", level: "medium" },
  { word: "cube", hint: "To multiply a number by itself three times.", level: "medium" },
  { word: "cube root", hint: "A number that when cubed gives the original number.", level: "medium" },
  
  // Ratios, Proportions & Percentages
  { word: "ratio", hint: "A comparison of two quantities by division.", level: "medium" },
  { word: "rate", hint: "A ratio comparing different types of quantities.", level: "medium" },
  { word: "unit rate", hint: "A rate with a denominator of 1.", level: "medium" },
  { word: "proportion", hint: "An equation stating that two ratios are equal.", level: "medium" },
  { word: "cross multiply", hint: "Multiplying diagonally across an equation to solve proportions.", level: "medium" },
  { word: "percent", hint: "A ratio expressed as a fraction of 100.", level: "medium" },
  { word: "percentage", hint: "An amount expressed as parts per hundred.", level: "medium" },
  { word: "discount", hint: "A reduction in price.", level: "medium" },
  { word: "markup", hint: "An increase added to a cost.", level: "medium" },
  { word: "sales tax", hint: "A percentage added to the cost of goods.", level: "medium" },
  { word: "tip", hint: "An amount of money given as a percentage of a bill.", level: "medium" },
  { word: "commission", hint: "Payment based on a percentage of sales.", level: "medium" },
  { word: "interest", hint: "Money paid for borrowing or earned from saving.", level: "medium" },
  { word: "principal", hint: "The original amount of money borrowed or invested.", level: "medium" },
  { word: "simple interest", hint: "Interest calculated only on the principal.", level: "medium" },
  { word: "compound interest", hint: "Interest calculated on principal and accumulated interest.", level: "medium" },
  
  // Number Theory & Properties
  { word: "prime number", hint: "A number greater than 1 with exactly two factors: 1 and itself.", level: "medium" },
  { word: "composite number", hint: "A number with more than two factors.", level: "medium" },
  { word: "prime factorization", hint: "Expressing a number as a product of its prime factors.", level: "medium" },
  { word: "multiple", hint: "A number that can be divided by another number without remainder.", level: "medium" },
  { word: "common multiple", hint: "A multiple shared by two or more numbers.", level: "medium" },
  { word: "least common multiple", hint: "The smallest multiple common to two or more numbers.", level: "medium" },
  { word: "greatest common factor", hint: "The largest factor shared by two or more numbers.", level: "medium" },
  { word: "divisibility rule", hint: "A shortcut to determine if one number divides another evenly.", level: "medium" },
  { word: "absolute value", hint: "The distance of a number from zero on a number line.", level: "medium" },
  { word: "opposite", hint: "A number the same distance from zero but on the opposite side.", level: "medium" },
  { word: "reciprocal", hint: "The inverse of a fraction, obtained by swapping numerator and denominator.", level: "medium" },
  { word: "rational number", hint: "A number that can be expressed as a fraction.", level: "medium" },
  { word: "irrational number", hint: "A number that cannot be expressed as a simple fraction.", level: "medium" },
  { word: "real number", hint: "Any rational or irrational number.", level: "medium" },
  
  // Geometry - Angles & Lines
  { word: "angle", hint: "The figure formed by two rays sharing a common endpoint.", level: "medium" },
  { word: "acute angle", hint: "An angle measuring less than 90 degrees.", level: "medium" },
  { word: "right angle", hint: "An angle measuring exactly 90 degrees.", level: "medium" },
  { word: "obtuse angle", hint: "An angle measuring more than 90 but less than 180 degrees.", level: "medium" },
  { word: "straight angle", hint: "An angle measuring exactly 180 degrees.", level: "medium" },
  { word: "reflex angle", hint: "An angle measuring more than 180 degrees but less than 360.", level: "medium" },
  { word: "complementary angles", hint: "Two angles whose measures add up to 90 degrees.", level: "medium" },
  { word: "supplementary angles", hint: "Two angles whose measures add up to 180 degrees.", level: "medium" },
  { word: "adjacent angles", hint: "Angles that share a common vertex and side.", level: "medium" },
  { word: "vertical angles", hint: "Opposite angles formed by intersecting lines.", level: "medium" },
  { word: "parallel lines", hint: "Lines in the same plane that never intersect.", level: "medium" },
  { word: "perpendicular lines", hint: "Lines that intersect at right angles.", level: "medium" },
  { word: "intersecting lines", hint: "Lines that cross at a point.", level: "medium" },
  { word: "transversal", hint: "A line that crosses two or more parallel lines.", level: "medium" },
  { word: "corresponding angles", hint: "Angles in the same position at different intersections.", level: "medium" },
  { word: "alternate interior angles", hint: "Interior angles on opposite sides of a transversal.", level: "medium" },
  { word: "bisect", hint: "To divide into two equal parts.", level: "medium" },
  { word: "angle bisector", hint: "A ray dividing an angle into two equal angles.", level: "medium" },
  { word: "midpoint", hint: "The point exactly halfway between two endpoints.", level: "medium" },
  
  // Geometry - Polygons & Circles
  { word: "polygon", hint: "A closed shape with straight sides.", level: "medium" },
  { word: "regular polygon", hint: "A polygon with all sides and angles equal.", level: "medium" },
  { word: "irregular polygon", hint: "A polygon with sides or angles that are not all equal.", level: "medium" },
  { word: "quadrilateral", hint: "A polygon with four sides.", level: "medium" },
  { word: "parallelogram", hint: "A quadrilateral with opposite sides parallel.", level: "medium" },
  { word: "trapezoid", hint: "A quadrilateral with at least one pair of parallel sides.", level: "medium" },
  { word: "rhombus", hint: "A parallelogram with all sides equal.", level: "medium" },
  { word: "kite", hint: "A quadrilateral with two pairs of adjacent equal sides.", level: "medium" },
  { word: "diagonal", hint: "A line segment connecting non-adjacent vertices.", level: "medium" },
  { word: "interior angle", hint: "An angle inside a polygon.", level: "medium" },
  { word: "exterior angle", hint: "An angle outside a polygon formed by extending a side.", level: "medium" },
  { word: "sum of angles", hint: "The total of all angles in a polygon.", level: "medium" },
  { word: "radius", hint: "A line from the center to any point on a circle.", level: "medium" },
  { word: "diameter", hint: "A line through the center of a circle touching two points on circumference.", level: "medium" },
  { word: "circumference", hint: "The distance around a circle.", level: "medium" },
  { word: "pi", hint: "The ratio of a circle's circumference to its diameter, approximately 3.14159.", level: "medium" },
  { word: "chord", hint: "A line segment connecting two points on a circle.", level: "medium" },
  { word: "arc", hint: "A portion of the circumference of a circle.", level: "medium" },
  { word: "semicircle", hint: "Half of a circle.", level: "medium" },
  { word: "sector", hint: "A pie-shaped portion of a circle.", level: "medium" },
  { word: "tangent", hint: "A line that touches a circle at exactly one point.", level: "medium" },
  { word: "central angle", hint: "An angle with vertex at the center of a circle.", level: "medium" },
  
  // 3D Geometry & Measurement
  { word: "prism", hint: "A 3D shape with two parallel congruent bases.", level: "medium" },
  { word: "rectangular prism", hint: "A prism with rectangular bases.", level: "medium" },
  { word: "triangular prism", hint: "A prism with triangular bases.", level: "medium" },
  { word: "surface area", hint: "The total area of all surfaces of a 3D shape.", level: "medium" },
  { word: "lateral surface area", hint: "The surface area excluding the bases.", level: "medium" },
  { word: "net", hint: "A flat pattern that folds into a 3D shape.", level: "medium" },
  { word: "cross section", hint: "The shape formed by slicing through a 3D object.", level: "medium" },
  
  // Statistics & Probability
  { word: "statistics", hint: "The study of collecting, analyzing, and interpreting data.", level: "medium" },
  { word: "data set", hint: "A collection of numbers or values.", level: "medium" },
  { word: "mean", hint: "The average of a set of numbers.", level: "medium" },
  { word: "median", hint: "The middle value in a sorted list of numbers.", level: "medium" },
  { word: "mode", hint: "The value that appears most frequently in a data set.", level: "medium" },
    { word: "range", hint: "The difference between the highest and lowest values.", level: "medium" },
  { word: "outlier", hint: "A value much higher or lower than other values in a set.", level: "medium" },
  { word: "frequency", hint: "How often a value occurs in a data set.", level: "medium" },
  { word: "frequency table", hint: "A table showing how often each value appears.", level: "medium" },
  { word: "histogram", hint: "A bar graph showing frequency distribution.", level: "medium" },
  { word: "line graph", hint: "A graph using points connected by lines to show change over time.", level: "medium" },
  { word: "scatter plot", hint: "A graph showing the relationship between two variables.", level: "medium" },
  { word: "correlation", hint: "A measure of how two variables change together.", level: "medium" },
  { word: "probability", hint: "The measure of how likely an event is to occur.", level: "medium" },
  { word: "outcome", hint: "A possible result of an experiment.", level: "medium" },
  { word: "event", hint: "A set of outcomes from an experiment.", level: "medium" },
  { word: "sample space", hint: "The set of all possible outcomes.", level: "medium" },
  { word: "theoretical probability", hint: "Probability based on reasoning about outcomes.", level: "medium" },
  { word: "experimental probability", hint: "Probability based on actual experiments.", level: "medium" },
  { word: "tree diagram", hint: "A diagram showing all possible outcomes.", level: "medium" },
  { word: "combination", hint: "A selection of items where order does not matter.", level: "medium" },
  { word: "permutation", hint: "An arrangement of items where order matters.", level: "medium" },

  // Functions & Relations
  { word: "function", hint: "A relation where each input has exactly one output.", level: "medium" },
  { word: "domain", hint: "The set of all possible input values for a function.", level: "medium" },
  { word: "range", hint: "The set of all possible output values of a function.", level: "medium" },
  { word: "input", hint: "The value put into a function.", level: "medium" },
  { word: "output", hint: "The value that comes out of a function.", level: "medium" },
  { word: "function notation", hint: "Using f(x) to represent a function.", level: "medium" },
  { word: "linear function", hint: "A function whose graph is a straight line.", level: "medium" },
  { word: "quadratic function", hint: "A function of the form f(x) = ax² + bx + c.", level: "medium" },
  { word: "parabola", hint: "The U-shaped graph of a quadratic function.", level: "medium" },
  { word: "vertex", hint: "The highest or lowest point on a parabola.", level: "medium" },
  { word: "axis of symmetry", hint: "A line dividing a parabola into mirror images.", level: "medium" },

  // Transformations
  { word: "transformation", hint: "Changing a figure's position or size.", level: "medium" },
  { word: "translation", hint: "Sliding a figure without turning or flipping.", level: "medium" },
  { word: "reflection", hint: "Flipping a figure over a line.", level: "medium" },
  { word: "rotation", hint: "Turning a figure around a point.", level: "medium" },
  { word: "dilation", hint: "Enlarging or reducing a figure proportionally.", level: "medium" },
  { word: "scale factor", hint: "The ratio of corresponding lengths in similar figures.", level: "medium" },
  { word: "similar", hint: "Figures that have the same shape but not necessarily the same size.", level: "medium" },
  { word: "congruent", hint: "Figures that have the same shape and size.", level: "medium" },

  // === ADVANCED LEVEL (Grades 10-12) === [150 words]

  // Advanced Algebra
  { word: "polynomial", hint: "An expression with multiple terms involving variables and exponents.", level: "hard" },
  { word: "monomial", hint: "A polynomial with one term.", level: "hard" },
  { word: "binomial", hint: "A polynomial with two terms.", level: "hard" },
  { word: "trinomial", hint: "A polynomial with three terms.", level: "hard" },
  { word: "degree", hint: "The highest exponent in a polynomial.", level: "hard" },
  { word: "leading coefficient", hint: "The coefficient of the term with the highest degree.", level: "hard" },
  { word: "synthetic division", hint: "A shortcut method for dividing polynomials.", level: "hard" },
  { word: "remainder theorem", hint: "If a polynomial f(x) is divided by (x-c), the remainder is f(c).", level: "hard" },
  { word: "factor theorem", hint: "x-c is a factor of f(x) if and only if f(c)=0.", level: "hard" },
  { word: "rational root theorem", hint: "Helps find possible rational roots of a polynomial.", level: "hard" },
  { word: "complex number", hint: "A number with real and imaginary parts.", level: "hard" },
  { word: "imaginary number", hint: "A number that when squared gives a negative result.", level: "hard" },
  { word: "complex conjugate", hint: "A complex number with the same real part but opposite imaginary part.", level: "hard" },
  { word: "absolute value", hint: "Distance from zero on the complex plane.", level: "hard" },

  // Quadratic Equations & Functions
  { word: "quadratic equation", hint: "An equation of the form ax² + bx + c = 0.", level: "hard" },
  { word: "quadratic formula", hint: "x = [-b ± √(b²-4ac)] / 2a used to solve quadratic equations.", level: "hard" },
  { word: "discriminant", hint: "b²-4ac, determines the nature of quadratic roots.", level: "hard" },
  { word: "completing the square", hint: "A method for solving quadratic equations.", level: "hard" },
  { word: "vertex form", hint: "f(x) = a(x-h)² + k, shows vertex of parabola.", level: "hard" },
  { word: "focus", hint: "A fixed point used to define a parabola.", level: "hard" },
  { word: "directrix", hint: "A fixed line used to define a parabola.", level: "hard" },

  // Exponential & Logarithmic Functions
  { word: "exponential function", hint: "A function where the variable is in the exponent.", level: "hard" },
  { word: "logarithm", hint: "The exponent to which a base must be raised to produce a given number.", level: "hard" },
  { word: "natural logarithm", hint: "Logarithm with base e.", level: "hard" },
  { word: "common logarithm", hint: "Logarithm with base 10.", level: "hard" },
  { word: "logarithmic function", hint: "The inverse of an exponential function.", level: "hard" },
  { word: "exponential growth", hint: "Growth at a rate proportional to current value.", level: "hard" },
  { word: "exponential decay", hint: "Decrease at a rate proportional to current value.", level: "hard" },
  { word: "half-life", hint: "Time for a quantity to reduce to half its initial value.", level: "hard" },
  { word: "compound interest", hint: "Interest calculated on principal and accumulated interest.", level: "hard" },

  // Trigonometry
  { word: "trigonometry", hint: "Study of relationships between angles and sides of triangles.", level: "hard" },
  { word: "sine", hint: "Trigonometric ratio of opposite side to hypotenuse.", level: "hard" },
  { word: "cosine", hint: "Trigonometric ratio of adjacent side to hypotenuse.", level: "hard" },
  { word: "tangent", hint: "Trigonometric ratio of opposite side to adjacent side.", level: "hard" },
  { word: "cosecant", hint: "Reciprocal of sine.", level: "hard" },
  { word: "secant", hint: "Reciprocal of cosine.", level: "hard" },
  { word: "cotangent", hint: "Reciprocal of tangent.", level: "hard" },
  { word: "unit circle", hint: "Circle with radius 1 centered at origin.", level: "hard" },
  { word: "radian", hint: "Angle measure based on arc length.", level: "hard" },
  { word: "amplitude", hint: "The height of a trigonometric function from its midline.", level: "hard" },
  { word: "period", hint: "The horizontal length of one cycle of a trigonometric function.", level: "hard" },
  { word: "frequency", hint: "Number of cycles per unit in a trigonometric function.", level: "hard" },
  { word: "phase shift", hint: "Horizontal shift of a trigonometric function.", level: "hard" },
  { word: "trigonometric identity", hint: "An equation true for all values of the variables.", level: "hard" },
  { word: "pythagorean identity", hint: "sin²θ + cos²θ = 1", level: "hard" },
  { word: "double angle formula", hint: "Identities for sin(2θ) and cos(2θ).", level: "hard" },
  { word: "law of sines", hint: "Relates sides and angles in any triangle.", level: "hard" },
  { word: "law of cosines", hint: "Relates sides and angles in any triangle.", level: "hard" },

  // Advanced Geometry
  { word: "conic sections", hint: "Curves formed by intersecting a plane with a cone.", level: "hard" },
  { word: "ellipse", hint: "Set of points where sum of distances to two foci is constant.", level: "hard" },
  { word: "hyperbola", hint: "Set of points where difference of distances to two foci is constant.", level: "hard" },
  { word: "locus", hint: "Set of points satisfying given conditions.", level: "hard" },
  { word: "inscribed angle", hint: "Angle with vertex on a circle and sides containing chords.", level: "hard" },
  { word: "circumscribed", hint: "A figure drawn around another, touching it at points.", level: "hard" },
  { word: "inscribed", hint: "A figure drawn inside another, touching it at points.", level: "hard" },
  { word: "apothem", hint: "Distance from center to midpoint of a side in regular polygon.", level: "hard" },

  // Vectors & Matrices
  { word: "vector", hint: "A quantity having both magnitude and direction.", level: "hard" },
  { word: "magnitude", hint: "The length or size of a vector.", level: "hard" },
  { word: "direction", hint: "The orientation of a vector in space.", level: "hard" },
  { word: "scalar", hint: "A quantity having only magnitude, no direction.", level: "hard" },
  { word: "dot product", hint: "A way to multiply vectors resulting in a scalar.", level: "hard" },
  { word: "cross product", hint: "A way to multiply vectors resulting in another vector.", level: "hard" },
  { word: "matrix", hint: "A rectangular array of numbers arranged in rows and columns.", level: "hard" },
  { word: "determinant", hint: "A scalar value that can be computed from a square matrix.", level: "hard" },
  { word: "inverse matrix", hint: "A matrix that when multiplied by the original gives identity matrix.", level: "hard" },
  { word: "identity matrix", hint: "A square matrix with 1s on diagonal and 0s elsewhere.", level: "hard" },
  { word: "transpose", hint: "Flipping a matrix over its diagonal.", level: "hard" },
  { word: "system of equations", hint: "Multiple equations with multiple variables.", level: "hard" },
  { word: "gaussian elimination", hint: "A method for solving systems of linear equations.", level: "hard" },

  // Calculus - Limits & Continuity
  { word: "calculus", hint: "The mathematical study of continuous change.", level: "hard" },
  { word: "limit", hint: "The value that a function approaches as the input approaches some value.", level: "hard" },
  { word: "continuity", hint: "A function is continuous if it has no breaks or jumps.", level: "hard" },
  { word: "discontinuity", hint: "A point where a function is not continuous.", level: "hard" },
  { word: "asymptote", hint: "A line that a curve approaches but never touches.", level: "hard" },
  { word: "vertical asymptote", hint: "A vertical line that a function approaches.", level: "hard" },
  { word: "horizontal asymptote", hint: "A horizontal line that a function approaches.", level: "hard" },
  { word: "squeeze theorem", hint: "A method for finding limits by bounding functions.", level: "hard" },

  // Calculus - Derivatives
  { word: "derivative", hint: "Measures the instantaneous rate of change of a function.", level: "hard" },
  { word: "differentiation", hint: "The process of finding the derivative of a function.", level: "hard" },
  { word: "power rule", hint: "A rule for finding derivatives of power functions.", level: "hard" },
  { word: "product rule", hint: "A rule for finding derivatives of products of functions.", level: "hard" },
  { word: "quotient rule", hint: "A rule for finding derivatives of quotients of functions.", level: "hard" },
  { word: "chain rule", hint: "A rule for finding derivatives of composite functions.", level: "hard" },
  { word: "critical point", hint: "A point where the derivative is zero or undefined.", level: "hard" },
  { word: "local maximum", hint: "The highest point in a small region of a function.", level: "hard" },
  { word: "local minimum", hint: "The lowest point in a small region of a function.", level: "hard" },
  { word: "inflection point", hint: "A point where concavity changes.", level: "hard" },
  { word: "concavity", hint: "The direction a curve bends.", level: "hard" },
  { word: "optimization", hint: "Finding maximum or minimum values of functions.", level: "hard" },
  { word: "related rates", hint: "Finding rates of change of related quantities.", level: "hard" },

  // Calculus - Integrals
  { word: "integral", hint: "Represents accumulation or area under a curve.", level: "hard" },
  { word: "integration", hint: "The process of finding the integral of a function.", level: "hard" },
  { word: "antiderivative", hint: "A function whose derivative is the given function.", level: "hard" },
  { word: "definite integral", hint: "An integral with specified limits of integration.", level: "hard" },
  { word: "indefinite integral", hint: "An integral without specified limits.", level: "hard" },
  { word: "fundamental theorem of calculus", hint: "Links differentiation and integration.", level: "hard" },
  { word: "u-substitution", hint: "A method for evaluating integrals by substitution.", level: "hard" },
  { word: "integration by parts", hint: "A method for evaluating integrals of products.", level: "hard" },
  { word: "area between curves", hint: "The area enclosed by two or more curves.", level: "hard" },
  { word: "volume of revolution", hint: "Volume created by rotating a curve around an axis.", level: "hard" },

  // Probability & Statistics
  { word: "normal distribution", hint: "Bell-shaped curve describing many natural phenomena.", level: "hard" },
  { word: "standard deviation", hint: "A measure of how spread out numbers are.", level: "hard" },
  { word: "variance", hint: "The square of the standard deviation.", level: "hard" },
  { word: "z-score", hint: "The number of standard deviations from the mean.", level: "hard" },
  { word: "confidence interval", hint: "A range of values likely to contain a population parameter.", level: "hard" },
  { word: "hypothesis testing", hint: "A method for testing claims about populations.", level: "hard" },
  { word: "regression", hint: "Finding relationships between variables.", level: "hard" },
  { word: "correlation coefficient", hint: "A measure of the strength of linear relationship.", level: "hard" },

  // Sequences & Series
  { word: "arithmetic sequence", hint: "A sequence with constant difference between terms.", level: "hard" },
  { word: "geometric sequence", hint: "A sequence with constant ratio between terms.", level: "hard" },
  { word: "arithmetic series", hint: "The sum of an arithmetic sequence.", level: "hard" },
  { word: "geometric series", hint: "The sum of a geometric sequence.", level: "hard" },
  { word: "convergence", hint: "Approaching a finite limit.", level: "hard" },
  { word: "divergence", hint: "Not approaching a finite limit.", level: "hard" },
  { word: "taylor series", hint: "Representing functions as infinite polynomials.", level: "hard" },
  { word: "maclaurin series", hint: "Taylor series centered at zero.", level: "hard" },

  // Differential Equations
  { word: "differential equation", hint: "An equation involving derivatives of a function.", level: "hard" },
  { word: "ordinary differential equation", hint: "A DE with one independent variable.", level: "hard" },
  { word: "partial differential equation", hint: "A DE with multiple independent variables.", level: "hard" },
  { word: "separation of variables", hint: "A method for solving certain differential equations.", level: "hard" },
  { word: "initial value problem", hint: "A differential equation with given initial conditions.", level: "hard" },

  // Advanced Topics
  { word: "complex analysis", hint: "Study of functions of complex variables.", level: "hard" },
  { word: "number theory", hint: "Study of properties and relationships of numbers.", level: "hard" },
  { word: "abstract algebra", hint: "Study of algebraic structures like groups and rings.", level: "hard" },
  { word: "linear algebra", hint: "Study of vectors, vector spaces, and linear transformations.", level: "hard" },
  { word: "topology", hint: "Study of properties preserved through continuous deformations.", level: "hard" },
  { word: "combinatorics", hint: "Study of counting, arrangement, and combination.", level: "hard" },
  { word: "graph theory", hint: "Study of graphs and networks.", level: "hard" },
  { word: "game theory", hint: "Study of mathematical models of strategic interaction.", level: "hard" },
  { word: "fractal", hint: "A complex geometric shape with self-similarity.", level: "hard" },
  { word: "chaos theory", hint: "Study of behavior in dynamical systems sensitive to initial conditions.", level: "hard" }
];